INSERT INTO Country (CountryCode, CountryName) VALUES
('AFG','Afghanistan'),
('ALB','Albania'),
('DZA','Algeria'),
('ASM','American Samoa'),
('AND','Andorra'),
('AGO','Angola'),
('ARG','Argentina'),
('ARM','Armenia'),
('ABW','Aruba' ),
('AUS','Australia'),
('AUT','Austria'),
('AZE','Azerbaijan'),
('BHS','Bahamas'),
('BHR','Bahrain'),
('BGD','Bangladesh'),
('BLR','Belarus'),
('BEL','Belgium'),
('BLZ','Belize'),
('BEN','Benin'),
('BMU','Bermuda'),
('BTN','Bhutan'),
('BOL','Bolivia'),
('BIH','Bosnia and Herzegovina'),
('BWA','Botswana'),
('BRA','Brazil'),
('BGR','Bulgaria'),
('BFA','Burkina Faso'),
('BDI','Burundi'),
('KHM','Cambodia'),
('CMR','Cameroon'),
('CAN','Canada'),
('CAF','Central African Republic'),
('TCD','Chad'),
('CHL','Chile'),
('CHN','China'),
('COL','Colombia'),
('COM','Comoros'),
('COG','Congo'),
('COD','Congo'),
('CRI','Costa Rica'),
('HRV','Croatia'),
('CUB','Cuba'),
('CYP','Cyprus'),
('CZE','Czech Republic'),
('DNK','Denmark'),
('DJI','Djibouti'),
('DMA','Dominica'),
('DOM','Dominican Republic'),
('ECU','Ecuador'),
('EGY','Egypt'),
('SLV','El Salvador'),
('ERI','Eritrea'),
('EST','Estonia'),
('ETH','Ethiopia'),
('FRO','Faroe Islands'),
('FJI','Republic of Fij'),
('FIN','Finland'),
('FRA','France'),
('GUF','French Guiana'),
('PYF','French Polynesia'),
('GAB','Gabon'),
('GMB','Gambia'),
('GEO','Georgia'),
('DEU','Germany'),
('GHA','Ghana'),
('GRC','Greece'),
('GRL','Greenland'),
('GLP','Guadeloupe'),
('GTM','Guatemala'),
('GIN','Guinea'),
('GNB','Guinea-Bissau'),
('GUY','Guyana'),
('HTI','Haiti'),
('VAT','Holy See (Vatican City State)'),
('HND','Honduras'),
('HKG','Hong Kong'),
('HUN','Hungary'),
('ISL','Iceland'),
('IND','India'),
('IDN','Indonesia'),
('IRN','Iran'),
('IRQ','Iraq'),
('IRL','Ireland'),
('ISR','Israel'),
('ITA','Italy'),
('JAM','Jamaica'),
('JPN','Japan'),
('JOR','Jordan'),
('KAZ','Kazakhstan'),
('KEN','Kenya'),
('KIR','Kiribati'),
('KWT','Kuwait'),
('KGZ','Kyrgyzstan'),
('LVA','Latvia'),
('LBN','Lebanon'),
('LSO','Lesotho'),
('LBR','Liberia'),
('LBY','Libyan Arab Jamahiriya'),
('LIE','Liechtenstein'),
('LTU','Lithuania'),
('LUX','Luxembourg'),
('MAC','Macao'),
('MDG','Madagascar'),
('MWI','Malawi'),
('MYS','Malaysia'),
('MDV','Maldives'),
('MLI','Mali'),
('MLT','Malta'),
('MRT','Mauritania'),
('MUS','Mauritius'),
('MEX','Mexico'),
('MCO','Monaco'),
('MNG','Mongolia'),
('MSR','Montserrat'),
('MAR','Morocco'),
('MOZ','Mozambique'),
('MMR','Myanmar'),
('NAM','Namibia'),
('NPL','Nepal'),
('NLD','Netherlands'),
('ANT','Netherlands Antilles'),
('NCL','New Caledonia'),
('NZL','New Zealand'),
('NIC','Nicaragua'),
('NOR','Norway'),
('OMN','Oman'),
('PAK','Pakistan'),
('PLW','Palau'),
('PAN','Panama'),
('PNG','Papua New Guinea'),
('PRY','Paraguay'),
('PER','Peru'),
('PHL','Philippines'),
('POL','Poland'),
('PRT','Portugal'),
('PRI','Puerto Rico'),
('QAT','Qatar'),
('ROM','Romania'),
('RUS','Russian Federation'),
('RWA','Rwanda'),
('WSM','Samoa'),
('SMR','San Marino'),
('SAU','Saudi Arabia'),
('SEN','Senegal'),
('SYC','Seychelles'),
('SLE','Sierra Leone'),
('SGP','Singapore'),
('SVK','Slovakia'),
('SVN','Slovenia'),
('SOM','Somalia'),
('ZAF','South Africa'),
('ESP','Spain'),
('LKA','Sri Lanka'),
('SDN','Sudan'),
('SWE','Sweden'),
('CHE','Switzerland'),
('SYR','Syrian Arab Republic'),
('TJK','Tajikistan'),
('TZA','Tanzania'),
('THA','Thailand'),
('TON','Tonga'),
('TUN','Tunisia'),
('TUR','Turkey'),
('TKM','Turkmenistan'),
('UGA','Uganda'),
('UKR','Ukraine'),
('ARE','United Arab Emirates'),
('GBR','United Kingdom'),
('USA','United States'),
('URY','Uruguay'),
('UZB','Uzbekistan'),
('VEN','Venezuela'),
('VNM','Viet Nam'),
('YEM','Yemen'),
('ZMB','Zambia'),
('ZWE','Zimbabwe');

INSERT INTO ColorScheme (ColorSchemeName, HighlightColor, BackgroundPrimary, BackgroundSecondary, BackgroundTernary, Light) VALUES ("Green", '#90CA9C', '#151617', '#1E2021', '#2F3233', '#D8D8D8' );
INSERT INTO ColorScheme (ColorSchemeName, HighlightColor, BackgroundPrimary, BackgroundSecondary, BackgroundTernary, Light) VALUES ("Red", '#C98F92', '#171715', '#21211E', '#32332F', '#D9D9D9' );
INSERT INTO ColorScheme (ColorSchemeName, HighlightColor, BackgroundPrimary, BackgroundSecondary, BackgroundTernary, Light) VALUES ("Blue", '#8FA4C9', '#171517', '#201E21', '#322F33', '#D9D9D9' );

INSERT INTO `System` (ServiceDescription, Rules, PhoneNumber, SystemEmail, `Address`, ColorSchemeId) VALUES ('Welcome to Bottom Shelf! Explore new recipe ideas by browsing the communitys submissions. Through tags and our search system, you can find exactly the drink you had in mind. If you dont feel inspired, go to Explore page… ', '1.Dont lie, dont steal, 2.be a good neighbor, 3.live laugh live', '00 00 00 00', 'bottomshelf@dummyEmail.com', 'Denmark Esbjerh 6700', 1);

INSERT INTO `Role` (RoleId, RoleName) VALUES (NULL,'User');
INSERT INTO `Role` (RoleId, RoleName) VALUES (NULL,'Admin');

INSERT INTO Badge (BadgeId, BadgeName) VALUES (NULL,'Recipe Enthusiast');
INSERT INTO Badge (BadgeId, BadgeName) VALUES (NULL,'Beloved By The People');
INSERT INTO Badge (BadgeId, BadgeName) VALUES (NULL,'Recipe Specialist');

INSERT INTO Tag (TagId, TagName) VALUES (NULL,'Easy');
INSERT INTO Tag (TagId, TagName) VALUES (NULL,'Intermediate');
INSERT INTO Tag (TagId, TagName) VALUES (NULL,'Hard');

INSERT INTO EntityStatus (StatusId, StatusName) VALUES (NULL,'Active');
INSERT INTO EntityStatus (StatusId, StatusName) VALUES (NULL,'Banned');
INSERT INTO EntityStatus (StatusId, StatusName) VALUES (NULL,'Reported');
INSERT INTO EntityStatus (StatusId, StatusName) VALUES (NULL,'Deleted');

INSERT INTO `User` (UserId, Email,UserPassword, Username, DateOfBirth, ProfileImgBlob, BioDescription, PostCount, CountryCode, RoleId, StatusId) 
VALUES (NULL,'test@lol.com', 'something123', 'ProudTester', '1999-11-11', NULL,'I existed only to test',  0,  'POL', 1, 1);

INSERT INTO `User` (UserId, Email,UserPassword, Username, DateOfBirth, ProfileImgBlob, BioDescription, PostCount, CountryCode, RoleId, StatusId) 
VALUES (NULL,'monkey@lol.com', 'monkeyPass', 'MonkeyFromATree', '200-01-12', NULL,'Test Or Not To Test',  0,  'DNK', 1, 1);


INSERT INTO Post (PostId, Title, PostDescription, IsPublic, IsSticky, ReactionCount, CommentCount, LatestCommentId, UserId, ChildPostId, StatusId)
VALUES (NULL,'First Post', 'Describing the post always', TRUE, FALSE, 0, 0, NULL, 1, NULL, 1);
INSERT INTO Post (PostId, Title, PostDescription, IsPublic, IsSticky, ReactionCount, CommentCount, LatestCommentId, UserId, ChildPostId, StatusId)
VALUES (NULL,'Another Post', 'Just a beer', TRUE, FALSE, 0, 0, NULL, 1, NULL, 1);
